@startuml

class Card {
  + Card(r : Rank, s : Suit)
  + getRank() : Rank
  + getSuit() : Suit
  + toString() : string
  + printCard(separator : string) : void
}

@enduml

@startuml

class Deck {
	+ Deck(numberDecks : int)
  + reset(numberDecks : int)
	+ shuffle() : void
	+ popCard() : Card
	+ printDeck() : void
  - cards : vector<Card>
}

@enduml

@startuml

class Player {
 + Player()
 + addCard(card Card) : void
 + playCard() : Card
 + printHand() : void
 - hand : dequeu<Card>
}

@enduml